# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import contacts_pb2 as contacts__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in contacts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContactServiceStub(object):
    """================================================================
    CONTACT SERVICE
    ================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetContact = channel.unary_unary(
                '/lkern.contacts.v1.ContactService/GetContact',
                request_serializer=contacts__pb2.GetContactRequest.SerializeToString,
                response_deserializer=contacts__pb2.ContactResponse.FromString,
                _registered_method=True)
        self.GetContactByCode = channel.unary_unary(
                '/lkern.contacts.v1.ContactService/GetContactByCode',
                request_serializer=contacts__pb2.GetContactByCodeRequest.SerializeToString,
                response_deserializer=contacts__pb2.ContactResponse.FromString,
                _registered_method=True)
        self.GetContactsBulk = channel.unary_unary(
                '/lkern.contacts.v1.ContactService/GetContactsBulk',
                request_serializer=contacts__pb2.GetContactsBulkRequest.SerializeToString,
                response_deserializer=contacts__pb2.ContactsBulkResponse.FromString,
                _registered_method=True)
        self.GetContactsByRole = channel.unary_unary(
                '/lkern.contacts.v1.ContactService/GetContactsByRole',
                request_serializer=contacts__pb2.GetContactsByRoleRequest.SerializeToString,
                response_deserializer=contacts__pb2.ContactsByRoleResponse.FromString,
                _registered_method=True)
        self.ValidateContact = channel.unary_unary(
                '/lkern.contacts.v1.ContactService/ValidateContact',
                request_serializer=contacts__pb2.ValidateContactRequest.SerializeToString,
                response_deserializer=contacts__pb2.ValidateContactResponse.FromString,
                _registered_method=True)
        self.GetContactSummary = channel.unary_unary(
                '/lkern.contacts.v1.ContactService/GetContactSummary',
                request_serializer=contacts__pb2.GetContactSummaryRequest.SerializeToString,
                response_deserializer=contacts__pb2.ContactSummaryResponse.FromString,
                _registered_method=True)


class ContactServiceServicer(object):
    """================================================================
    CONTACT SERVICE
    ================================================================

    """

    def GetContact(self, request, context):
        """Single contact operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContactByCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContactsBulk(self, request, context):
        """Bulk operations (for other microservices)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContactsByRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateContact(self, request, context):
        """Validation (for duplicate detection)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContactSummary(self, request, context):
        """Quick lookup (lightweight)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContactServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetContact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContact,
                    request_deserializer=contacts__pb2.GetContactRequest.FromString,
                    response_serializer=contacts__pb2.ContactResponse.SerializeToString,
            ),
            'GetContactByCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContactByCode,
                    request_deserializer=contacts__pb2.GetContactByCodeRequest.FromString,
                    response_serializer=contacts__pb2.ContactResponse.SerializeToString,
            ),
            'GetContactsBulk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContactsBulk,
                    request_deserializer=contacts__pb2.GetContactsBulkRequest.FromString,
                    response_serializer=contacts__pb2.ContactsBulkResponse.SerializeToString,
            ),
            'GetContactsByRole': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContactsByRole,
                    request_deserializer=contacts__pb2.GetContactsByRoleRequest.FromString,
                    response_serializer=contacts__pb2.ContactsByRoleResponse.SerializeToString,
            ),
            'ValidateContact': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateContact,
                    request_deserializer=contacts__pb2.ValidateContactRequest.FromString,
                    response_serializer=contacts__pb2.ValidateContactResponse.SerializeToString,
            ),
            'GetContactSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContactSummary,
                    request_deserializer=contacts__pb2.GetContactSummaryRequest.FromString,
                    response_serializer=contacts__pb2.ContactSummaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lkern.contacts.v1.ContactService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lkern.contacts.v1.ContactService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContactService(object):
    """================================================================
    CONTACT SERVICE
    ================================================================

    """

    @staticmethod
    def GetContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lkern.contacts.v1.ContactService/GetContact',
            contacts__pb2.GetContactRequest.SerializeToString,
            contacts__pb2.ContactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContactByCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lkern.contacts.v1.ContactService/GetContactByCode',
            contacts__pb2.GetContactByCodeRequest.SerializeToString,
            contacts__pb2.ContactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContactsBulk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lkern.contacts.v1.ContactService/GetContactsBulk',
            contacts__pb2.GetContactsBulkRequest.SerializeToString,
            contacts__pb2.ContactsBulkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContactsByRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lkern.contacts.v1.ContactService/GetContactsByRole',
            contacts__pb2.GetContactsByRoleRequest.SerializeToString,
            contacts__pb2.ContactsByRoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lkern.contacts.v1.ContactService/ValidateContact',
            contacts__pb2.ValidateContactRequest.SerializeToString,
            contacts__pb2.ValidateContactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContactSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lkern.contacts.v1.ContactService/GetContactSummary',
            contacts__pb2.GetContactSummaryRequest.SerializeToString,
            contacts__pb2.ContactSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
