import { Meta, StoryObj } from '@storybook/react';
import { CreateIssueModal } from './CreateIssueModal';
declare const meta: Meta<typeof CreateIssueModal>;
export default meta;
type Story = StoryObj<typeof CreateIssueModal>;
export declare const BasicUser: Story;
export declare const StandardUser: Story;
export declare const AdvancedUser: Story;
export declare const WithRoleTabs: Story;
export declare const WithInitialData: Story;
export declare const LoadingState: Story;
export declare const WithClearButton: Story;
export declare const WithoutClearButton: Story;
export declare const BugReport: Story;
export declare const FeatureRequest: Story;
export declare const Improvement: Story;
export declare const Question: Story;
export declare const Features: Story;
export declare const RoleComparison: Story;
