import { Meta, StoryObj } from '@storybook/react';
import { Spinner } from './Spinner';
declare const meta: Meta<typeof Spinner>;
export default meta;
type Story = StoryObj<typeof Spinner>;
export declare const Small: Story;
export declare const Medium: Story;
export declare const Large: Story;
export declare const WithLabel: Story;
export declare const WithLabelLarge: Story;
export declare const CustomColorPrimary: Story;
export declare const CustomColorSuccess: Story;
export declare const CustomColorError: Story;
export declare const PageLoading: Story;
export declare const ButtonLoading: Story;
export declare const InlineLoading: Story;
export declare const AllSizes: Story;
export declare const ColorVariations: Story;
