import { Meta, StoryObj } from '@storybook/react';
import { DebugBar } from './DebugBar';
declare const meta: Meta<typeof DebugBar>;
export default meta;
type Story = StoryObj<typeof DebugBar>;
export declare const LightMode: Story;
export declare const DarkMode: Story;
export declare const PageContext: Story;
export declare const ModalContext: Story;
export declare const HighActivity: Story;
export declare const LowActivity: Story;
export declare const JustOpened: Story;
export declare const LongModalName: Story;
export declare const Hidden: Story;
export declare const LightAndDark: Story;
export declare const DifferentContextTypes: Story;
