import { Meta, StoryObj } from '@storybook/react';
import { ReportButton } from './ReportButton';
declare const meta: Meta<typeof ReportButton>;
export default meta;
type Story = StoryObj<typeof ReportButton>;
export declare const TopRight: Story;
export declare const TopLeft: Story;
export declare const BottomRight: Story;
export declare const BottomLeft: Story;
export declare const WithModal: Story;
export declare const MultiplePositions: Story;
export declare const WithPageTemplate: Story;
