import { Meta, StoryObj } from '@storybook/react';
import { SectionEditModal } from './SectionEditModal';
declare const meta: Meta<typeof SectionEditModal>;
export default meta;
type Story = StoryObj<typeof SectionEditModal>;
export declare const PersonalInfo: Story;
export declare const AllFieldTypes: Story;
export declare const WithValidation: Story;
export declare const SmallSize: Story;
export declare const LargeSize: Story;
export declare const WithClearButton: Story;
export declare const ContactBasicInfo: Story;
export declare const IssueMetadata: Story;
export declare const Features: Story;
