/*
 * ================================================================
 * FILE: contacts.types.ts
 * PATH: packages/config/src/translations/types/contacts.types.ts
 * DESCRIPTION: Contacts page translation types (auto-generated)
 * VERSION: v1.0.0
 * UPDATED: 2025-12-19
 * GENERATED: DO NOT EDIT MANUALLY - generated by generate-page.js
 * ================================================================
 */

export interface ContactsPageTranslations {
  permanentDeleteError: string;
  restoreConfirm: string;
  restoreSuccess: string;
  permanentDeleteConfirm: string;
  permanentDeleteSuccess: string;
  bulkDelete: {
    title: string;
    titlePermanent: string;
    titleMixed: string;
    softMessage: string;
    hardMessage: string;
    mixedMessage: string;
    minioMessage: string;
  };
  minioUnavailable: {
    title: string;
    message: string;
    markForDeletion: string;
    markedForDeletion: string;
    retryDelete: string;
  };
  title: string;
  subtitle: string;
  breadcrumb: string;
  searchPlaceholder: string;
  newItemButton: string;
  newItemClicked: string;
  showInactiveLabel: string;
  deleteConfirm: string;
  deleteSuccess: string;
  detailsTitle: string;
  selectedCount: string;
  clearSelection: string;
  bulkExport: string;
  bulkDeleteConfirm: string;
  bulkDeleteSuccess: string;
  columns: {
    contact_code: string;
    display_name: string;
    contact_type: string;
    primary_email: string;
    primary_phone: string;
    roles: string;
    created_at: string;
  };
  details: {
    contact_code: string;
    display_name: string;
    contact_type: string;
    primary_email: string;
    primary_phone: string;
    roles: string;
    created_at: string;
  };
  filters: {
    typeTitle: string;
    typePerson: string;
    typeCompany: string;
    typeOrganizationalUnit: string;
    roleTitle: string;
    roleSupplier: string;
    roleCustomer: string;
    roleEmployee: string;
    rolePartner: string;
  };
  quickFilters: {
    persons: string;
    companies: string;
    suppliers: string;
    customers: string;
  };
  statuses: {
    person: string;
    company: string;
    organizational_unit: string;
  };
}
