/*
 * ================================================================
 * FILE: issues.types.ts
 * PATH: packages/config/src/translations/types/issues.types.ts
 * DESCRIPTION: Issues page translation types (auto-generated)
 * VERSION: v1.0.0
 * UPDATED: 2025-11-08
 * GENERATED: DO NOT EDIT MANUALLY - generated by generate-page.js
 * ================================================================
 */

export interface IssuesPageTranslations {
  title: string;
  subtitle: string;
  breadcrumb: string;
  searchPlaceholder: string;
  newItemButton: string;
  newItemClicked: string;
  showInactiveLabel: string;
  deleteConfirm: string;
  deleteSuccess: string;
  restoreConfirm: string;
  restoreSuccess: string;
  permanentDeleteConfirm: string;
  permanentDeleteSuccess: string;
  detailsTitle: string;
  selectedCount: string;
  clearSelection: string;
  bulkExport: string;
  bulkDeleteConfirm: string;
  bulkDeleteSuccess: string;
  exportSuccess: string;
  exportZipStarted: string;
  exportZipLoading: string;
  exportZipError: string;
  fetchError: string;
  columns: {
    issue_code: string;
    title: string;
    type: string;
    severity: string;
    status: string;
    priority: string;
    created_by: string;
    created_at: string;
  };
  system: string;
  user: string;
  details: {
    issue_code: string;
    title: string;
    type: string;
    severity: string;
    status: string;
    priority: string;
    created_at: string;
    itemDetails: string;
    id: string;
    description: string;
    reporterId: string;
    assigneeId: string;
    resolution: string;
    timeline: string;
    updated: string;
    resolved: string;
    closed: string;
    deleted: string;
    classification: string;
    category: string;
    developerInfo: string;
    browser: string;
    os: string;
    url: string;
    errorType: string;
    errorMessage: string;
    notAvailable: string;
    attachments: string;
    noAttachments: string;
    clickToDownload: string;
    deletedItem: string;
    // Attachment availability status
    attachmentChecking: string;
    attachmentAvailable: string;
    attachmentUnavailable: string;
    attachmentError: string;
    attachmentMissing: string;
    attachmentServiceDown: string;
    attachmentCannotDownload: string;
  };
  filters: {
    typeTitle: string;
    typeBug: string;
    typeFeature: string;
    typeImprovement: string;
    typeQuestion: string;
    severityTitle: string;
    severityMinor: string;
    severityModerate: string;
    severityMajor: string;
    severityBlocker: string;
    statusTitle: string;
    statusOpen: string;
    statusAssigned: string;
    statusInProgress: string;
    statusResolved: string;
    statusClosed: string;
    statusRejected: string;
    priorityTitle: string;
    priorityLow: string;
    priorityMedium: string;
    priorityHigh: string;
    priorityCritical: string;
  };
  quickFilters: {
    blockers: string;
    myIssues: string;
    systemIssues: string;
    unassigned: string;
  };
  types: {
    bug: string;
    feature: string;
    improvement: string;
    question: string;
  };
  typeSelect: {
    title: string;
  };
  deletionAudit: {
    title: string;
    status: string;
    summary: string;
    itemCode: string;
    filesFound: string;
    filesDeleted: string;
    startedAt: string;
    completedAt: string;
    errorMessage: string;
    failedFiles: string;
    viewAuditLog: string;
    deletionFailed: string;
    deletionPending: string;
    softDeleted: string;
    statusValues: {
      pending: string;
      completed: string;
      failed: string;
      partial: string;
    };
  };
  bulkDelete: {
    title: string;
    titlePermanent: string;
    titleMixed: string;
    softMessage: string;
    hardMessage: string;
    mixedMessage: string;
    minioMessage: string;
  };
  minioUnavailable: {
    title: string;
    message: string;
    okButton: string;
    markForDeletion: string;
    markedForDeletion: string;
    retryDelete: string;
  };
  minioCreateError: {
    title: string;
    message: string;
    createWithoutFiles: string;
    cancel: string;
    retryWithFiles: string;
  };
  minioExportError: {
    title: string;
    message: string;
    exportWithoutAttachments: string;
    retryWithAttachments: string;
  };
  createSuccessWithoutFiles: string;
  createSuccessNoFiles: string;
  createError: {
    title: string;
    serviceUnavailable: string;
    generic: string;
    retry: string;
    checkingDependencies: string;
    serviceDown: string;
    takingLonger: string;
    retrying: string;
  };
  updateError: {
    title: string;
    serviceUnavailable: string;
    serviceDown: string;
    takingLonger: string;
    retrying: string;
    generic: string;
    retry: string;
  };
  createSuccess: string;
  updateSuccess: string;
  permanentDeleteError: string;
  view: {
    overview: string;
    description: string;
    technicalDetails: string;
    developerInfo: string;
    resolution: string;
    attachments: string;
    noAttachments: string;
    people: string;
    timeline: string;
    activity: string;
    unassigned: string;
    noReporter: string;
    noActivity: string;
  };
  exportErrors: {
    title: string;
    successCount: string;
    deletedTitle: string;
    missingAttachmentsTitle: string;
    missingAttachmentsModalTitle: string;
    missingAttachmentsMessage: string;
    downloadWithoutMissing: string;
    minioTitle: string;
  };
  exportPartialSuccess: string;
  exportPartialAttachments: string;
  exportZipNoContent: string;
  exportSuccessNoAttachments: string;
  attachmentEdit: {
    title: string;
    existingTitle: string;
    addNewTitle: string;
    markDelete: string;
    undoDelete: string;
    deletionWarning: string;
    totalCount: string;
    saveSuccess: string;
    saveError: string;
    confirmDeleteTitle: string;
    confirmDeleteMessage: string;
    confirmDeleteWarning: string;
    confirmDeleteButton: string;
  };
}
