/*
 * ================================================================
 * FILE: issues.types.ts
 * PATH: packages/config/src/translations/types/issues.types.ts
 * DESCRIPTION: Issues page translation types (auto-generated)
 * VERSION: v1.0.0
 * UPDATED: 2025-11-08
 * GENERATED: DO NOT EDIT MANUALLY - generated by generate-page.js
 * ================================================================
 */

export interface IssuesPageTranslations {
  title: string;
  subtitle: string;
  breadcrumb: string;
  searchPlaceholder: string;
  newItemButton: string;
  newItemClicked: string;
  showInactiveLabel: string;
  deleteConfirm: string;
  deleteSuccess: string;
  restoreConfirm: string;
  restoreSuccess: string;
  permanentDeleteConfirm: string;
  permanentDeleteSuccess: string;
  detailsTitle: string;
  selectedCount: string;
  clearSelection: string;
  bulkExport: string;
  bulkDeleteConfirm: string;
  bulkDeleteSuccess: string;
  columns: {
    issue_code: string;
    title: string;
    type: string;
    severity: string;
    status: string;
    priority: string;
    created_at: string;
  };
  details: {
    issue_code: string;
    title: string;
    type: string;
    severity: string;
    status: string;
    priority: string;
    created_at: string;
  };
  filters: {
    typeTitle: string;
    typeBug: string;
    typeFeature: string;
    typeImprovement: string;
    typeQuestion: string;
    severityTitle: string;
    severityMinor: string;
    severityModerate: string;
    severityMajor: string;
    severityBlocker: string;
    statusTitle: string;
    statusOpen: string;
    statusAssigned: string;
    statusInProgress: string;
    statusResolved: string;
    statusClosed: string;
    statusRejected: string;
    priorityTitle: string;
    priorityLow: string;
    priorityMedium: string;
    priorityHigh: string;
    priorityCritical: string;
  };
  quickFilters: {
    blockers: string;
    myIssues: string;
    unassigned: string;
  };
  types: {
    bug: string;
    feature: string;
    improvement: string;
    question: string;
  };
  typeSelect: {
    title: string;
  };
  deletionAudit: {
    title: string;
    status: string;
    summary: string;
    itemCode: string;
    filesFound: string;
    filesDeleted: string;
    startedAt: string;
    completedAt: string;
    errorMessage: string;
    failedFiles: string;
    viewAuditLog: string;
    deletionFailed: string;
    deletionPending: string;
    softDeleted: string;
    statusValues: {
      pending: string;
      completed: string;
      failed: string;
      partial: string;
    };
  };
}
