/*
 * ================================================================
 * FILE: orders.types.ts
 * PATH: packages/config/src/translations/types/orders.types.ts
 * DESCRIPTION: Orders page translation types (auto-generated)
 * VERSION: v1.0.0
 * UPDATED: 2025-11-08
 * GENERATED: DO NOT EDIT MANUALLY - generated by generate-page.js
 * ================================================================
 */

export interface OrdersPageTranslations {
  title: string;
  subtitle: string;
  breadcrumb: string;
  searchPlaceholder: string;
  newItemButton: string;
  newItemClicked: string;
  showInactiveLabel: string;
  deleteConfirm: string;
  deleteSuccess: string;
  detailsTitle: string;
  selectedCount: string;
  clearSelection: string;
  bulkExport: string;
  bulkDeleteConfirm: string;
  bulkDeleteSuccess: string;
  columns: {
    id: string;
    customer: string;
    status: string;
    priority: string;
    total: string;
    dueDate: string;
  };
  details: {
    id: string;
    customer: string;
    status: string;
    priority: string;
    total: string;
    dueDate: string;
  };
  filters: {
    statusTitle: string;
    statusActive: string;
    statusPending: string;
    statusInactive: string;
    priorityTitle: string;
    priorityLow: string;
    priorityMedium: string;
    priorityHigh: string;
  };
  quickFilters: {
    highValue: string;
    overdue: string;
  };
}
