import { Meta, StoryObj } from '@storybook/react';
import { Badge } from './Badge';
declare const meta: Meta<typeof Badge>;
export default meta;
type Story = StoryObj<typeof Badge>;
export declare const Success: Story;
export declare const Warning: Story;
export declare const Error: Story;
export declare const Info: Story;
export declare const Neutral: Story;
export declare const SizeSmall: Story;
export declare const SizeMedium: Story;
export declare const SizeLarge: Story;
export declare const WithDot: Story;
export declare const WithDotError: Story;
export declare const WithDotWarning: Story;
export declare const StatusBadges: Story;
export declare const CountBadges: Story;
export declare const AllVariants: Story;
export declare const AllSizes: Story;
