import { Meta, StoryObj } from '@storybook/react';
import { InfoHint } from './InfoHint';
declare const meta: Meta<typeof InfoHint>;
export default meta;
type Story = StoryObj<typeof InfoHint>;
export declare const Top: Story;
export declare const Bottom: Story;
export declare const Left: Story;
export declare const Right: Story;
export declare const SizeSmall: Story;
export declare const SizeMedium: Story;
export declare const SizeLarge: Story;
export declare const ShortContent: Story;
export declare const LongContent: Story;
export declare const CustomWidth: Story;
export declare const RichContent: Story;
export declare const FormFieldHelp: Story;
export declare const TableHeaderHelp: Story;
export declare const SettingsHelp: Story;
export declare const AllPositions: Story;
export declare const AllSizes: Story;
