import { Meta, StoryObj } from '@storybook/react';
import { FilteredDataGrid } from './FilteredDataGrid';
declare const meta: Meta<typeof FilteredDataGrid>;
export default meta;
type Story = StoryObj<typeof FilteredDataGrid>;
export declare const Default: Story;
export declare const WithFilters: Story;
export declare const WithStatusColors: Story;
export declare const WithSelection: Story;
export declare const WithExpansion: Story;
export declare const WithInactiveToggle: Story;
export declare const WithNewItemButton: Story;
export declare const WithCustomSearch: Story;
export declare const WithQuickFilters: Story;
export declare const LoadingState: Story;
export declare const ErrorState: Story;
export declare const EmptyState: Story;
export declare const CompactMode: Story;
export declare const SmallPageSize: Story;
export declare const LargePageSize: Story;
export declare const FullFeatured: Story;
