import { Meta, StoryObj } from '@storybook/react';
import { Card } from './Card';
declare const meta: Meta<typeof Card>;
export default meta;
type Story = StoryObj<typeof Card>;
export declare const Default: Story;
export declare const Outlined: Story;
export declare const Elevated: Story;
export declare const Accent: Story;
export declare const Clickable: Story;
export declare const NoHover: Story;
export declare const WithImage: Story;
export declare const WithList: Story;
export declare const WithFooter: Story;
export declare const AllVariants: Story;
