import { Meta, StoryObj } from '@storybook/react';
import { AuthRoleSwitcher } from './AuthRoleSwitcher';
declare const meta: Meta<typeof AuthRoleSwitcher>;
export default meta;
type Story = StoryObj<typeof AuthRoleSwitcher>;
export declare const Expanded: Story;
export declare const Collapsed: Story;
export declare const ExpandedAndCollapsed: Story;
export declare const KeyboardShortcuts: Story;
export declare const PermissionLevels: Story;
