import { Meta, StoryObj } from '@storybook/react';
import { ExportProgressModal } from './ExportProgressModal';
declare const meta: Meta<typeof ExportProgressModal>;
export default meta;
type Story = StoryObj<typeof ExportProgressModal>;
export declare const HealthCheck: Story;
export declare const DownloadingDeterminate: Story;
export declare const DownloadingIndeterminate: Story;
export declare const Processing: Story;
export declare const Complete: Story;
export declare const CSVExport: Story;
export declare const JSONExport: Story;
export declare const ZIPWithManyFiles: Story;
export declare const WithCancel: Story;
export declare const NoAttachments: Story;
export declare const LargeFile: Story;
export declare const ProgressPhases: Story;
export declare const Features: Story;
