import { Meta, StoryObj } from '@storybook/react';
import { Toast } from './Toast';
declare const meta: Meta<typeof Toast>;
export default meta;
type Story = StoryObj<typeof Toast>;
export declare const Success: Story;
export declare const Error: Story;
export declare const Warning: Story;
export declare const Info: Story;
export declare const WithCopiedContent: Story;
export declare const LongCopiedContent: Story;
export declare const SaveSuccess: Story;
export declare const DeleteError: Story;
export declare const FormValidationWarning: Story;
export declare const NetworkInfo: Story;
export declare const AllTypes: Story;
export declare const WithAndWithoutClose: Story;
