import { Meta, StoryObj } from '@storybook/react';
import { Pagination } from './Pagination';
declare const meta: Meta<typeof Pagination>;
export default meta;
type Story = StoryObj<typeof Pagination>;
export declare const Default: Story;
export declare const FewPages: Story;
export declare const ManyPages: Story;
export declare const FirstPage: Story;
export declare const LastPage: Story;
export declare const SinglePage: Story;
export declare const WithToggle: Story;
export declare const Disabled: Story;
export declare const SmallItemsPerPage: Story;
export declare const LargeItemsPerPage: Story;
export declare const InteractiveDemo: Story;
