import { Meta, StoryObj } from '@storybook/react';
import { EmptyState } from './EmptyState';
declare const meta: Meta<typeof EmptyState>;
export default meta;
type Story = StoryObj<typeof EmptyState>;
export declare const Default: Story;
export declare const WithoutDescription: Story;
export declare const WithAction: Story;
export declare const SizeSmall: Story;
export declare const SizeMedium: Story;
export declare const SizeLarge: Story;
export declare const NoContacts: Story;
export declare const NoSearchResults: Story;
export declare const NoOrders: Story;
export declare const NoNotifications: Story;
export declare const NoMessages: Story;
export declare const EmptyInbox: Story;
export declare const NoFavorites: Story;
export declare const NoFilterResults: Story;
export declare const ErrorState: Story;
export declare const ComingSoon: Story;
export declare const AllSizes: Story;
export declare const CommonIcons: Story;
