import { Meta, StoryObj } from '@storybook/react';
import { Textarea } from './Textarea';
declare const meta: Meta<typeof Textarea>;
export default meta;
type Story = StoryObj<typeof Textarea>;
export declare const Default: Story;
export declare const SmallSize: Story;
export declare const LargeSize: Story;
export declare const FullWidth: Story;
export declare const WithError: Story;
export declare const Valid: Story;
export declare const Disabled: Story;
export declare const WithValue: Story;
export declare const WithMaxLength: Story;
export declare const AllSizes: Story;
export declare const AllStates: Story;
export declare const UseCases: Story;
