import { Meta, StoryObj } from '@storybook/react';
import { FileUpload } from './FileUpload';
declare const meta: Meta<typeof FileUpload>;
export default meta;
type Story = StoryObj<typeof FileUpload>;
export declare const Default: Story;
export declare const WithError: Story;
export declare const CustomMaxFiles: Story;
export declare const CustomMaxSize: Story;
export declare const ImagesOnly: Story;
export declare const PDFOnly: Story;
export declare const WithoutDragDrop: Story;
export declare const WithoutPaste: Story;
export declare const WithoutHint: Story;
export declare const WithLimitExceededCallback: Story;
export declare const WithPasteLimitCallback: Story;
export declare const CompleteExample: Story;
