import { Meta, StoryObj } from '@storybook/react';
import { Button } from './Button';
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof Button>;
export declare const Primary: Story;
export declare const Secondary: Story;
export declare const Danger: Story;
export declare const DangerSubtle: Story;
export declare const Ghost: Story;
export declare const Success: Story;
export declare const SizeXS: Story;
export declare const SizeSmall: Story;
export declare const SizeMedium: Story;
export declare const SizeLarge: Story;
export declare const Loading: Story;
export declare const Disabled: Story;
export declare const FullWidth: Story;
export declare const WithIconLeft: Story;
export declare const WithIconRight: Story;
export declare const AllVariants: Story;
export declare const AllSizes: Story;
