import { Meta, StoryObj } from '@storybook/react';
import { FormField } from './FormField';
declare const meta: Meta<typeof FormField>;
export default meta;
type Story = StoryObj<typeof FormField>;
export declare const Default: Story;
export declare const Required: Story;
export declare const WithHelperText: Story;
export declare const WithError: Story;
export declare const FullWidth: Story;
export declare const ReservedMessageSpace: Story;
export declare const WithTextInput: Story;
export declare const WithTextarea: Story;
export declare const WithSelect: Story;
export declare const WithCharacterCounter: Story;
export declare const WithLabelHint: Story;
export declare const WithValidation: Story;
export declare const ControlledMode: Story;
export declare const CompleteForm: Story;
export declare const AllStates: Story;
