import { Meta, StoryObj } from '@storybook/react';
import { ConfirmModal } from './ConfirmModal';
declare const meta: Meta<typeof ConfirmModal>;
export default meta;
type Story = StoryObj<typeof ConfirmModal>;
export declare const SimpleConfirm: Story;
export declare const SimpleWithCustomButtons: Story;
export declare const SimpleLoading: Story;
export declare const DangerConfirm: Story;
export declare const DangerWithCustomKeyword: Story;
export declare const DangerLoading: Story;
export declare const WithSecondaryButton: Story;
export declare const WithSecondaryLoading: Story;
export declare const UnsavedChanges: Story;
export declare const DeleteContact: Story;
export declare const ClearForm: Story;
export declare const AllVariants: Story;
