import { Meta, StoryObj } from '@storybook/react';
import { ExportButton } from './ExportButton';
declare const meta: Meta<typeof ExportButton>;
export default meta;
type Story = StoryObj<typeof ExportButton>;
export declare const Default: Story;
export declare const CSVOnly: Story;
export declare const AllFormats: Story;
export declare const Disabled: Story;
export declare const CustomLabel: Story;
export declare const WithClassName: Story;
export declare const WithDataGrid: Story;
export declare const MultipleButtons: Story;
