import { Meta, StoryObj } from '@storybook/react';
import { Modal } from './Modal';
declare const meta: Meta<typeof Modal>;
export default meta;
type Story = StoryObj<typeof Modal>;
export declare const Default: Story;
export declare const WithFooter: Story;
export declare const WithEnhancedFooter: Story;
export declare const SizeSmall: Story;
export declare const SizeMedium: Story;
export declare const SizeLarge: Story;
export declare const AlignmentTop: Story;
export declare const AlignmentCenter: Story;
export declare const AlignmentBottom: Story;
export declare const Loading: Story;
export declare const WithUnsavedChanges: Story;
export declare const NoCloseButton: Story;
export declare const CloseOnBackdropClick: Story;
export declare const Draggable: Story;
export declare const DragDisabled: Story;
export declare const CustomMaxWidth: Story;
export declare const AllSizes: Story;
