import { Meta, StoryObj } from '@storybook/react';
import { Radio } from './Radio';
declare const meta: Meta<typeof Radio>;
export default meta;
type Story = StoryObj<typeof Radio>;
export declare const Default: Story;
export declare const Checked: Story;
export declare const Disabled: Story;
export declare const DisabledChecked: Story;
export declare const WithError: Story;
export declare const AllStates: Story;
export declare const RadioGroup: Story;
export declare const RadioGroupWithDisabled: Story;
export declare const RadioGroupWithError: Story;
