/*
 * ================================================================
 * FILE: contacts.ts
 * PATH: packages/config/src/translations/pages/contacts.ts
 * DESCRIPTION: Contacts page SK translations (auto-generated)
 * VERSION: v1.0.0
 * UPDATED: 2025-12-19
 * GENERATED: DO NOT EDIT MANUALLY - generated by generate-page.js
 * ================================================================
 */

export const contactsPageSk = {
  permanentDeleteError: 'Chyba pri trvalom vymazaní položky {name}: {error}',
  restoreConfirm: 'Naozaj chcete obnoviť položku {name}?',
  restoreSuccess: 'Položka {name} bola úspešne obnovená',
  permanentDeleteConfirm: 'Naozaj chcete TRVALO vymazať položku {name}? Táto akcia je NEVRATNÁ!',
  permanentDeleteSuccess: 'Položka {name} bola trvalo vymazaná',
  bulkDelete: {
    title: 'Vymazať položky',
    titlePermanent: 'NATRVALO vymazať',
    titleMixed: 'Vymazať položky',
    softMessage: 'Naozaj chcete vymazať {count} položiek? Položky budú označené ako vymazané.',
    hardMessage: 'NATRVALO vymazať {count} položiek? Túto akciu NEMOŽNO vrátiť späť! Napíšte "ano" pre potvrdenie.',
    mixedMessage: 'Soft delete {softCount} aktívnych + Hard delete {hardCount} vymazaných položiek? Napíšte "ano" pre potvrdenie.',
    minioMessage: 'Súborové úložisko (MinIO) je nedostupné. {count} položiek sa nedá trvalo vymazať. Chcete ich označiť na neskoršie zmazanie?',
  },
  minioUnavailable: {
    title: '⚠️ Úložisko nedostupné',
    message: 'Súborové úložisko (MinIO) je momentálne nedostupné. Položka {code} sa nedá vymazať hneď. Chcete ju označiť na neskoršie zmazanie?',
    markForDeletion: 'Označiť na zmazanie',
    markedForDeletion: 'Položka {code} bola označená na neskoršie zmazanie',
    retryDelete: 'Skúsiť znova',
  },
  title: 'Kontakty',
  subtitle: 'Master Data Management - správa kontaktov',
  breadcrumb: 'Kontakty',
  searchPlaceholder: 'Hľadať kontakty podľa mena, kódu alebo emailu...',
  newItemButton: '+ Nový kontakt',
  newItemClicked: 'Vytvorenie nového kontaktu',
  showInactiveLabel: 'Zobraz vymazané kontakty',
  deleteConfirm: 'Naozaj chcete vymazať kontakt {name}?',
  deleteSuccess: 'Kontakt {name} bol úspešne vymazaný',
  detailsTitle: 'Detail kontaktu: {name}',
  selectedCount: 'Vybrané',
  clearSelection: 'Zrušiť výber',
  bulkExport: 'Exportovať {count} kontaktov',
  bulkDeleteConfirm: 'Naozaj chcete vymazať {count} kontaktov?',
  bulkDeleteSuccess: '{count} kontaktov bolo úspešne vymazaných',
  columns: {
    contact_code: 'Kód',
    display_name: 'Názov',
    contact_type: 'Typ',
    primary_email: 'Email',
    primary_phone: 'Telefón',
    roles: 'Roly',
    created_at: 'Vytvorené',
  },
  details: {
    contact_code: 'Kód kontaktu',
    display_name: 'Názov',
    contact_type: 'Typ kontaktu',
    primary_email: 'Primárny email',
    primary_phone: 'Primárny telefón',
    roles: 'Priradené roly',
    created_at: 'Dátum vytvorenia',
  },
  filters: {
    typeTitle: 'Typ kontaktu',
    typePerson: 'Osoba',
    typeCompany: 'Firma',
    typeOrganizationalUnit: 'Organizačná jednotka',
    roleTitle: 'Rola',
    roleSupplier: 'Dodávateľ',
    roleCustomer: 'Odberateľ',
    roleEmployee: 'Zamestnanec',
    rolePartner: 'Partner',
  },
  quickFilters: {
    persons: '👤 Osoby',
    companies: '🏢 Firmy',
    suppliers: '📦 Dodávatelia',
    customers: '🛒 Odberatelia',
  },
  // Edit Modal
  editContact: 'Upraviť kontakt: {name}',
  createContact: 'Vytvoriť nový kontakt',
  // Form sections
  sections: {
    basicInfo: 'Základné údaje',
    contactInfo: 'Kontaktné údaje',
    companyInfo: 'Údaje o firme',
    unitInfo: 'Údaje o jednotke',
  },
  // Form fields
  fields: {
    firstName: 'Meno',
    lastName: 'Priezvisko',
    titleBefore: 'Titul pred menom',
    titleAfter: 'Titul za menom',
    birthDate: 'Dátum narodenia',
    gender: 'Pohlavie',
    companyName: 'Názov firmy',
    registrationNumber: 'IČO',
    taxId: 'DIČ',
    vatId: 'IČ DPH',
    legalForm: 'Právna forma',
    unitName: 'Názov jednotky',
    unitType: 'Typ jednotky',
    parentCompany: 'Materská firma',
    primaryEmail: 'Primárny email',
    primaryPhone: 'Primárny telefón',
    primaryWebsite: 'Web stránka',
  },
  // Placeholders
  placeholders: {
    titleBefore: 'napr. Ing., Mgr.',
    titleAfter: 'napr. PhD., MBA',
    registrationNumber: 'napr. 12345678',
    taxId: 'napr. 2012345678',
    vatId: 'napr. SK2012345678',
  },
  // Gender options
  gender: {
    male: 'Muž',
    female: 'Žena',
    other: 'Iné',
  },
};
