/*
 * ================================================================
 * FILE: contacts.en.ts
 * PATH: packages/config/src/translations/pages/contacts.en.ts
 * DESCRIPTION: Contacts page EN translations (auto-generated)
 * VERSION: v1.0.0
 * UPDATED: 2025-12-20
 * GENERATED: DO NOT EDIT MANUALLY - generated by generate-page.js
 * ================================================================
 */

export const contactsPageEn = {
  permanentDeleteError: 'Error permanently deleting item {name}: {error}',
  restoreConfirm: 'Are you sure you want to restore item {name}?',
  restoreSuccess: 'Item {name} has been successfully restored',
  permanentDeleteConfirm: 'Are you sure you want to PERMANENTLY delete item {name}? This action is IRREVERSIBLE!',
  permanentDeleteSuccess: 'Item {name} has been permanently deleted',
  bulkDelete: {
    title: 'Delete Items',
    titlePermanent: 'PERMANENTLY Delete',
    titleMixed: 'Delete Items',
    softMessage: 'Are you sure you want to delete {count} items? Items will be marked as deleted.',
    hardMessage: 'PERMANENTLY delete {count} items? This action CANNOT be undone! Type "yes" to confirm.',
    mixedMessage: 'Soft delete {softCount} active + Hard delete {hardCount} deleted items? Type "yes" to confirm.',
    minioMessage: 'File storage (MinIO) is unavailable. {count} items cannot be permanently deleted. Do you want to mark them for later deletion?',
  },
  minioUnavailable: {
    title: '⚠️ Storage Unavailable',
    message: 'File storage (MinIO) is currently unavailable. Item {code} cannot be deleted immediately. Do you want to mark it for later deletion?',
    markForDeletion: 'Mark for deletion',
    markedForDeletion: 'Item {code} has been marked for later deletion',
    retryDelete: 'Retry',
  },
  title: 'Contacts',
  subtitle: 'Master Data Management - contact management',
  breadcrumb: 'Contacts',
  searchPlaceholder: 'Search contacts by name, code, or email...',
  newItemButton: '+ New Contact',
  newItemClicked: 'Creating new contact',
  showInactiveLabel: 'Show deleted contacts',
  deleteConfirm: 'Are you sure you want to delete contact {name}?',
  deleteSuccess: 'Contact {name} has been successfully deleted',
  detailsTitle: 'Contact Details: {name}',
  selectedCount: 'Selected',
  clearSelection: 'Clear selection',
  bulkExport: 'Export {count} contacts',
  bulkDeleteConfirm: 'Are you sure you want to delete {count} contacts?',
  bulkDeleteSuccess: '{count} contacts have been successfully deleted',
  columns: {
    contact_code: 'Code',
    display_name: 'Name',
    contact_type: 'Type',
    primary_email: 'Email',
    primary_phone: 'Phone',
    roles: 'Roles',
    created_at: 'Created',
  },
  details: {
    contact_code: 'Contact Code',
    display_name: 'Name',
    contact_type: 'Contact Type',
    primary_email: 'Primary Email',
    primary_phone: 'Primary Phone',
    roles: 'Assigned Roles',
    created_at: 'Creation Date',
  },
  filters: {
    typeTitle: 'Contact Type',
    typePerson: 'Person',
    typeCompany: 'Company',
    typeOrganizationalUnit: 'Organizational Unit',
    roleTitle: 'Role',
    roleSupplier: 'Supplier',
    roleCustomer: 'Customer',
    roleEmployee: 'Employee',
    rolePartner: 'Partner',
  },
  quickFilters: {
    persons: '👤 Persons',
    companies: '🏢 Companies',
    suppliers: '📦 Suppliers',
    customers: '🛒 Customers',
  },
  statuses: {
    person: 'Person',
    company: 'Company',
    organizational_unit: 'Org. Unit',
  },
};
