/*
 * ================================================================
 * FILE: contacts.en.ts
 * PATH: packages/config/src/translations/pages/contacts.en.ts
 * DESCRIPTION: Contacts page EN translations (auto-generated)
 * VERSION: v1.0.0
 * UPDATED: 2025-12-19
 * GENERATED: DO NOT EDIT MANUALLY - generated by generate-page.js
 * ================================================================
 */

export const contactsPageEn = {
  permanentDeleteError: 'Error permanently deleting item {name}: {error}',
  restoreConfirm: 'Are you sure you want to restore item {name}?',
  restoreSuccess: 'Item {name} has been successfully restored',
  permanentDeleteConfirm: 'Are you sure you want to PERMANENTLY delete item {name}? This action is IRREVERSIBLE!',
  permanentDeleteSuccess: 'Item {name} has been permanently deleted',
  bulkDelete: {
    title: 'Delete Items',
    titlePermanent: 'PERMANENTLY Delete',
    titleMixed: 'Delete Items',
    softMessage: 'Are you sure you want to delete {count} items? Items will be marked as deleted.',
    hardMessage: 'PERMANENTLY delete {count} items? This action CANNOT be undone! Type "yes" to confirm.',
    mixedMessage: 'Soft delete {softCount} active + Hard delete {hardCount} deleted items? Type "yes" to confirm.',
    minioMessage: 'File storage (MinIO) is unavailable. {count} items cannot be permanently deleted. Do you want to mark them for later deletion?',
  },
  minioUnavailable: {
    title: '⚠️ Storage Unavailable',
    message: 'File storage (MinIO) is currently unavailable. Item {code} cannot be deleted immediately. Do you want to mark it for later deletion?',
    markForDeletion: 'Mark for deletion',
    markedForDeletion: 'Item {code} has been marked for later deletion',
    retryDelete: 'Retry',
  },
  title: 'Contacts',
  subtitle: 'Master Data Management - contact management',
  breadcrumb: 'Contacts',
  searchPlaceholder: 'Search contacts by name, code, or email...',
  newItemButton: '+ New Contact',
  newItemClicked: 'Creating new contact',
  showInactiveLabel: 'Show deleted contacts',
  deleteConfirm: 'Are you sure you want to delete contact {name}?',
  deleteSuccess: 'Contact {name} has been successfully deleted',
  detailsTitle: 'Contact Details: {name}',
  selectedCount: 'Selected',
  clearSelection: 'Clear selection',
  bulkExport: 'Export {count} contacts',
  bulkDeleteConfirm: 'Are you sure you want to delete {count} contacts?',
  bulkDeleteSuccess: '{count} contacts have been successfully deleted',
  columns: {
    contact_code: 'Code',
    display_name: 'Name',
    contact_type: 'Type',
    primary_email: 'Email',
    primary_phone: 'Phone',
    roles: 'Roles',
    created_at: 'Created',
  },
  details: {
    contact_code: 'Contact Code',
    display_name: 'Name',
    contact_type: 'Contact Type',
    primary_email: 'Primary Email',
    primary_phone: 'Primary Phone',
    roles: 'Assigned Roles',
    created_at: 'Creation Date',
  },
  filters: {
    typeTitle: 'Contact Type',
    typePerson: 'Person',
    typeCompany: 'Company',
    typeOrganizationalUnit: 'Organizational Unit',
    roleTitle: 'Role',
    roleSupplier: 'Supplier',
    roleCustomer: 'Customer',
    roleEmployee: 'Employee',
    rolePartner: 'Partner',
  },
  quickFilters: {
    persons: '👤 Persons',
    companies: '🏢 Companies',
    suppliers: '📦 Suppliers',
    customers: '🛒 Customers',
  },
  // Edit Modal
  editContact: 'Edit Contact: {name}',
  createContact: 'Create New Contact',
  // Form sections
  sections: {
    basicInfo: 'Basic Information',
    contactInfo: 'Contact Information',
    companyInfo: 'Company Information',
    unitInfo: 'Unit Information',
  },
  // Form fields
  fields: {
    firstName: 'First Name',
    lastName: 'Last Name',
    titleBefore: 'Title (prefix)',
    titleAfter: 'Title (suffix)',
    birthDate: 'Date of Birth',
    gender: 'Gender',
    companyName: 'Company Name',
    registrationNumber: 'Registration Number',
    taxId: 'Tax ID',
    vatId: 'VAT ID',
    legalForm: 'Legal Form',
    unitName: 'Unit Name',
    unitType: 'Unit Type',
    parentCompany: 'Parent Company',
    primaryEmail: 'Primary Email',
    primaryPhone: 'Primary Phone',
    primaryWebsite: 'Website',
  },
  // Placeholders
  placeholders: {
    titleBefore: 'e.g. Dr., Prof.',
    titleAfter: 'e.g. PhD, MBA',
    registrationNumber: 'e.g. 12345678',
    taxId: 'e.g. 2012345678',
    vatId: 'e.g. SK2012345678',
  },
  // Gender options
  gender: {
    male: 'Male',
    female: 'Female',
    other: 'Other',
  },
};
