/*
 * ================================================================
 * FILE: issues.ts
 * PATH: packages/config/src/translations/pages/issues.ts
 * DESCRIPTION: Issues page SK translations (auto-generated)
 * VERSION: v1.0.0
 * UPDATED: 2025-11-08
 * GENERATED: DO NOT EDIT MANUALLY - generated by generate-page.js
 * ================================================================
 */

export const issuesPageSk = {
  title: 'Položky',
  subtitle: 'Sledovanie a správa položiek projektu',
  breadcrumb: 'Položky',
  searchPlaceholder: 'Hľadať položky podľa kódu, názvu alebo popisu...',
  newItemButton: '+ Nová položka',
  newItemClicked: 'Vytvorenie novej položky',
  showInactiveLabel: 'Zobraz vymazané položky',
  deleteConfirm: 'Naozaj chcete vymazať položku {name}?',
  deleteSuccess: 'Položka {name} bola úspešne vymazaná',
  detailsTitle: 'Detaily položky: {name}',
  selectedCount: 'Vybrané',
  clearSelection: 'Zrušiť výber',
  bulkExport: 'Exportovať {count} položiek',
  bulkDeleteConfirm: 'Naozaj chcete vymazať {count} položiek?',
  bulkDeleteSuccess: '{count} položiek bolo úspešne vymazaných',
  columns: {
    issue_code: 'Kód problému',
    title: 'Názov',
    type: 'Typ',
    severity: 'Závažnosť',
    status: 'Stav',
    priority: 'Priorita',
    created_at: 'Vytvorené',
  },
  details: {
    issue_code: 'Kód',
    title: 'Názov',
    type: 'Typ',
    severity: 'Závažnosť',
    status: 'Stav',
    priority: 'Priorita',
    created_at: 'Dátum vytvorenia',
  },
  filters: {
    typeTitle: 'Typ',
    typeBug: 'Chyba',
    typeFeature: 'Funkcia',
    typeImprovement: 'Vylepšenie',
    typeQuestion: 'Otázka',
    severityTitle: 'Závažnosť',
    severityMinor: 'Malá',
    severityModerate: 'Stredná',
    severityMajor: 'Veľká',
    severityBlocker: 'Blokujúca',
    statusTitle: 'Stav',
    statusOpen: 'Otvorený',
    statusAssigned: 'Priradený',
    statusInProgress: 'V riešení',
    statusResolved: 'Vyriešený',
    statusClosed: 'Uzatvorený',
    statusRejected: 'Odmietnutý',
    priorityTitle: 'Priorita',
    priorityLow: 'Nízka',
    priorityMedium: 'Stredná',
    priorityHigh: 'Vysoká',
    priorityCritical: 'Kritická',
  },
  quickFilters: {
    blockers: '🚨 Blokujúce',
    myIssues: '👤 Moje položky',
    unassigned: '📋 Nepriradené',
  },
  types: {
    bug: 'Chyba',
    feature: 'Funkcia',
    improvement: 'Vylepšenie',
    question: 'Otázka',
  },
  typeSelect: {
    title: 'Vyberte typ položky',
  },
};
