/*
 * ================================================================
 * FILE: issues.en.ts
 * PATH: packages/config/src/translations/pages/issues.en.ts
 * DESCRIPTION: Issues page EN translations (auto-generated)
 * VERSION: v1.0.0
 * UPDATED: 2025-11-08
 * GENERATED: DO NOT EDIT MANUALLY - generated by generate-page.js
 * ================================================================
 */

export const issuesPageEn = {
  title: 'Issues',
  subtitle: 'Track and manage project issues',
  breadcrumb: 'Issues',
  searchPlaceholder: 'Search issues by code, title, or description...',
  newItemButton: '+ New Issue',
  newItemClicked: 'Creating new issue',
  showInactiveLabel: 'Show deleted issues',
  deleteConfirm: 'Are you sure you want to delete issue {name}?',
  deleteSuccess: 'Issue {name} has been successfully deleted',
  detailsTitle: 'Issue Details: {name}',
  selectedCount: 'Selected',
  clearSelection: 'Clear selection',
  bulkExport: 'Export {count} issues',
  bulkDeleteConfirm: 'Are you sure you want to delete {count} issues?',
  bulkDeleteSuccess: '{count} issues have been successfully deleted',
  columns: {
    issue_code: 'Issue Code',
    title: 'Title',
    type: 'Type',
    severity: 'Severity',
    status: 'Status',
    priority: 'Priority',
    created_at: 'Created',
  },
  details: {
    issue_code: 'Code',
    title: 'Title',
    type: 'Type',
    severity: 'Severity',
    status: 'Status',
    priority: 'Priority',
    created_at: 'Creation Date',
  },
  filters: {
    typeTitle: 'Type',
    typeBug: 'Bug',
    typeFeature: 'Feature',
    typeImprovement: 'Improvement',
    typeQuestion: 'Question',
    severityTitle: 'Severity',
    severityMinor: 'Minor',
    severityModerate: 'Moderate',
    severityMajor: 'Major',
    severityBlocker: 'Blocker',
    statusTitle: 'Status',
    statusOpen: 'Open',
    statusAssigned: 'Assigned',
    statusInProgress: 'In Progress',
    statusResolved: 'Resolved',
    statusClosed: 'Closed',
    statusRejected: 'Rejected',
    priorityTitle: 'Priority',
    priorityLow: 'Low',
    priorityMedium: 'Medium',
    priorityHigh: 'High',
    priorityCritical: 'Critical',
  },
  quickFilters: {
    blockers: '🚨 Blockers',
    myIssues: '👤 My Issues',
    unassigned: '📋 Unassigned',
  },
  types: {
    bug: 'Bug',
    feature: 'Feature',
    improvement: 'Improvement',
    question: 'Question',
  },
  typeSelect: {
    title: 'Select Item Type',
  },
};
