/*
 * ================================================================
 * FILE: orders.en.ts
 * PATH: packages/config/src/translations/pages/orders.en.ts
 * DESCRIPTION: Orders page EN translations (auto-generated)
 * VERSION: v1.0.0
 * UPDATED: 2025-11-08
 * GENERATED: DO NOT EDIT MANUALLY - generated by generate-page.js
 * ================================================================
 */

export const ordersPageEn = {
  title: 'Orders',
  subtitle: 'Order Management',
  breadcrumb: 'Orders',
  searchPlaceholder: 'Search orders...',
  newItemButton: 'New Order',
  newItemClicked: 'You clicked New Order',
  showInactiveLabel: 'Show inactive',
  deleteConfirm: 'Are you sure you want to delete order {name}?',
  deleteSuccess: 'Order {name} has been successfully deleted',
  detailsTitle: 'Order Details: {name}',
  selectedCount: 'Selected',
  clearSelection: 'Clear selection',
  bulkExport: 'Export {count} orders',
  bulkDeleteConfirm: 'Are you sure you want to delete {count} orders?',
  bulkDeleteSuccess: '{count} orders have been successfully deleted',
  columns: {
    id: 'Order ID',
    customer: 'Customer',
    status: 'Status',
    priority: 'Priority',
    total: 'Total',
    dueDate: 'Due Date',
  },
  details: {
    id: 'ID',
    customer: 'Customer',
    status: 'Status',
    priority: 'Priority',
    total: 'Total Amount',
    dueDate: 'Due Date',
  },
  filters: {
    statusTitle: 'Status',
    statusActive: 'Active',
    statusPending: 'Pending',
    statusInactive: 'Inactive',
    priorityTitle: 'Priority',
    priorityLow: 'Low',
    priorityMedium: 'Medium',
    priorityHigh: 'High',
  },
  quickFilters: {
    highValue: 'High Value',
    overdue: 'Overdue',
  },
};
