/*
 * ================================================================
 * FILE: orders.ts
 * PATH: packages/config/src/translations/pages/orders.ts
 * DESCRIPTION: Orders page SK translations (auto-generated)
 * VERSION: v1.0.0
 * UPDATED: 2025-11-08
 * GENERATED: DO NOT EDIT MANUALLY - generated by generate-page.js
 * ================================================================
 */

export const ordersPageSk = {
  title: 'Objednávky',
  subtitle: 'Správa objednávok',
  breadcrumb: 'Objednávky',
  searchPlaceholder: 'Hľadať objednávky...',
  newItemButton: 'Nová objednávka',
  newItemClicked: 'Kliknul si na Nová objednávka',
  showInactiveLabel: 'Zobraz neaktívne',
  deleteConfirm: 'Naozaj chcete vymazať objednávku {name}?',
  deleteSuccess: 'Objednávka {name} bola úspešne vymazaná',
  detailsTitle: 'Detaily objednávky: {name}',
  selectedCount: 'Vybrané',
  clearSelection: 'Zrušiť výber',
  bulkExport: 'Exportovať {count} objednávok',
  bulkDeleteConfirm: 'Naozaj chcete vymazať {count} objednávok?',
  bulkDeleteSuccess: '{count} objednávok bolo úspešne vymazaných',
  columns: {
    id: 'ID objednávky',
    customer: 'Zákazník',
    status: 'Stav',
    priority: 'Priorita',
    total: 'Celkom',
    dueDate: 'Termín',
  },
  details: {
    id: 'ID',
    customer: 'Zákazník',
    status: 'Stav',
    priority: 'Priorita',
    total: 'Celková suma',
    dueDate: 'Termín',
  },
  filters: {
    statusTitle: 'Stav',
    statusActive: 'Aktívne',
    statusPending: 'Čakajúce',
    statusInactive: 'Neaktívne',
    priorityTitle: 'Priorita',
    priorityLow: 'Nízka',
    priorityMedium: 'Stredná',
    priorityHigh: 'Vysoká',
  },
  quickFilters: {
    highValue: 'Vysoká hodnota',
    overdue: 'Po termíne',
  },
};
