import { Meta, StoryObj } from '@storybook/react';
import { WizardProgress } from './WizardProgress';
declare const meta: Meta<typeof WizardProgress>;
export default meta;
type Story = StoryObj<typeof WizardProgress>;
export declare const Dots: Story;
export declare const Bar: Story;
export declare const Numbers: Story;
export declare const FirstStep: Story;
export declare const MiddleStep: Story;
export declare const LastStep: Story;
export declare const ThreeSteps: Story;
export declare const SevenSteps: Story;
export declare const AllVariants: Story;
export declare const ProgressSequence: Story;
