/*
 * ================================================================
 * FILE: system-constants.ts
 * PATH: packages/config/src/constants/system-constants.ts
 * DESCRIPTION: System-level constants for automated operations
 * VERSION: v1.0.0
 * UPDATED: 2025-12-04
 * ================================================================
 */

/**
 * System User ID - Reserved UUID for system-generated entities.
 *
 * Used for:
 * - Auto-generated Issues (data integrity problems, orphaned files)
 * - System audit logs
 * - Automated maintenance tasks
 *
 * This allows filtering system-generated vs user-generated records:
 * WHERE reporter_id = SYSTEM_USER_ID → system-generated
 * WHERE reporter_id != SYSTEM_USER_ID → user-generated
 *
 * Format: UUID v4 with recognizable pattern (all zeros except version/variant)
 */
export const SYSTEM_USER_ID = '00000000-0000-4000-8000-000000000001';

/**
 * System User Display Name - For UI display
 */
export const SYSTEM_USER_NAME = 'System';

/**
 * Issue categories that can be auto-generated by system
 */
export const SYSTEM_ISSUE_CATEGORIES = ['data_integrity'] as const;

/**
 * Default issue settings for system-generated issues
 */
export const SYSTEM_ISSUE_DEFAULTS = {
  category: 'data_integrity',
  type: 'bug',
  severity: 'moderate',
  priority: 'medium',
  status: 'open',
} as const;

// ================================================================
// TEST USERS (for development/testing)
// ================================================================

/**
 * Predefined test users for development and testing.
 * Can be switched in the Sidebar User tab.
 *
 * IDs can be overridden via environment variables:
 * - VITE_TEST_USER_PETER_ID
 * - VITE_TEST_USER_1_ID
 * - VITE_TEST_USER_2_ID
 * - VITE_TEST_USER_3_ID
 */
export interface TestUser {
  id: string;
  name: string;
  email: string;
  permissionLevel: number;
  role: 'basic' | 'standard' | 'advanced';
  description: string;
}

/**
 * Get environment variable with fallback.
 * Vite exposes env vars via import.meta.env
 */
const getEnvVar = (key: string, fallback: string): string => {
  // Check if running in browser with Vite
  if (typeof import.meta !== 'undefined' && import.meta.env) {
    return (import.meta.env as Record<string, string>)[key] || fallback;
  }
  // Node.js environment
  if (typeof process !== 'undefined' && process.env) {
    return process.env[key] || fallback;
  }
  return fallback;
};

/**
 * Test Users - Predefined users for development
 */
export const TEST_USERS: TestUser[] = [
  {
    id: getEnvVar('VITE_TEST_USER_PETER_ID', '00000000-0000-4000-8000-000000000100'),
    name: 'Peter Luhový',
    email: 'peter@lkern.local',
    permissionLevel: 100,
    role: 'advanced',
    description: 'Superuser (lvl 100)',
  },
  {
    id: getEnvVar('VITE_TEST_USER_1_ID', '00000000-0000-4000-8000-000000000101'),
    name: 'Test User 1',
    email: 'test1@lkern.local',
    permissionLevel: 25, // Basic lvl3 = 25
    role: 'basic',
    description: 'Basic (lvl3)',
  },
  {
    id: getEnvVar('VITE_TEST_USER_2_ID', '00000000-0000-4000-8000-000000000102'),
    name: 'Test User 2',
    email: 'test2@lkern.local',
    permissionLevel: 55, // Standard lvl3 = 55
    role: 'standard',
    description: 'Standard (lvl3)',
  },
  {
    id: getEnvVar('VITE_TEST_USER_3_ID', '00000000-0000-4000-8000-000000000103'),
    name: 'Test User 3',
    email: 'test3@lkern.local',
    permissionLevel: 70, // Advanced lvl2 = 70
    role: 'advanced',
    description: 'Advanced (lvl2)',
  },
];

/**
 * Get test user by ID
 */
export const getTestUserById = (id: string): TestUser | undefined => {
  return TEST_USERS.find((user) => user.id === id);
};

/**
 * Get test user by name (case-insensitive partial match)
 */
export const getTestUserByName = (name: string): TestUser | undefined => {
  const nameLower = name.toLowerCase();
  return TEST_USERS.find((user) => user.name.toLowerCase().includes(nameLower));
};
