import { Meta, StoryObj } from '@storybook/react';
import { Checkbox } from './Checkbox';
declare const meta: Meta<typeof Checkbox>;
export default meta;
type Story = StoryObj<typeof Checkbox>;
export declare const Default: Story;
export declare const Checked: Story;
export declare const Disabled: Story;
export declare const DisabledChecked: Story;
export declare const WithHelperText: Story;
export declare const WithError: Story;
export declare const Indeterminate: Story;
export declare const WithoutLabel: Story;
export declare const AllStates: Story;
export declare const GroupExample: Story;
